version: "3.5"

services:
  mysql:
    image: mysql:8.0.26
    container_name: database-mysql-test
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=nocountry#2023
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - nocountry
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql-test
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=nocountry2023
    networks:
    - nocountry
  postgres:
    image: postgres:alpine3.14
    container_name: database-postgres-test
    restart: always
    environment:
    - POSTGRES_PASSWORD=Aforo2552023
    ports:
    - 5434:5432
    networks:
    - nocountry
  mongo:
    image: mongo:5.0.2
    container_name: database-mongo-test
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=nocountry
    - MONGO_INITDB_ROOT_PASSWORD=nocountry#2023
    ports:
    - 27018:27017
    networks:
    - nocountry
  redis:
    image: redis:6.2.6
    command: --requirepass nocountry#2023
    container_name: database-redis-test
    restart: always
    environment:
    - REDIS_PASSWORD=nocountry#2023
    ports:
    - 6379:6379
    networks:
    - nocountry

networks:
  nocountry:
    name: nocountry

