springdoc:
  swagger-ui:
    path: /loans-application.html

spring:
  application:
    name: loans-application
  main:
    #Desactivo el Banner de Spring Boot de consola
    banner-mode: off
  datasource:
#   driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://20.121.214.190:1434;databaseName=user;encrypt=true;trustServerCertificate=true;
#    username: sa
#    password: nocountry2023

    #para testear con db en local
    #url: jdbc:${DB_URL}
    url: jdbc:mysql://localhost:3306/loan
    #username: ${DB_USER}
    username: root
    #password: ${DB_PASSWORD}
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  kafka:
    bootstrap-servers: 20.121.214.190:9092
    template:
      default-topic: account-topic
    #consumer:
      #bootstrap-servers: 20.121.214.190:9092
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #group-id: message-account-consumer

service:
  security:
    secure-key-username: NoCountryKeySecureUsername
    secure-key-password: NoCountryKeySecurePassword!

server:
  error:
    include-stacktrace: never
  port: 8083
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      #default-zone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka
      default-zone: http://localhost:8761/eureka



