---
app:
  jwt:
    expiration-in-minute: 5
    secret: RandomSecretKey123456789!RandomSecretKey123456789!RandomSecretKey123456789!
spring:
  application:
    name: security
  main:
    #Desactivo el Banner de Spring Boot de consola
    banner-mode: off
  datasource:
    url: jdbc:mysql://20.121.214.190:3307/account-db
    username: root
    password: nocountry#2023
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Connect kafka
  kafka:
    bootstrap-servers: 20.121.214.190:9092
    template:
      default-topic: account-topic

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

service:
  security:
    secure-key-username: NoCountryKeySecureUsername
    secure-key-password: NoCountryKeySecurePassword!

server:
  error:
<<<<<<< HEAD
    include-message: always
    include-binding-errors: always
=======
    include-stacktrace: never
>>>>>>> 1417018eb989b3c46e684571262b35d226cc084c
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
<<<<<<< HEAD
      default-zone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka
      #default-zone: http://localhost/eureka

management:
  tracing:
    sampling:
      probability: 1.0
=======
      default-zone: https://ssdfsdf.azurewebsites.net:8761/eureka
>>>>>>> 1417018eb989b3c46e684571262b35d226cc084c
...